# Generated by Django 2.1.7 on 2019-03-29 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trombinoscoop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='birth_name',
            new_name='birth_date',
        ),
    ]
